framework: mocha
tier: large
postMerge:
  pattern: 
    - "./test/*.ts"
preMerge:
  pattern:
    - "./test/*.ts"
preRun:
     command:
        - npm install
        - npm run build
postRun:
     command:
        - node --version
version: 1.0
