framework: mocha
preRun:
     command:
        - npm install
        - npm run prebuild
preMerge:
  pattern:
    - "./test/control.ts"
postMerge:
  pattern: 
    - "./test/control.ts"
postRun:
     command:
        - node --version
configFile: "mocharc.yml"
version: 1.0